### ISSUE TITLE
Including in pub.yaml causes pub to hang 

### ISSUE THREAD

**Issue by ArgentiApparatus** [dartist/stats.dart#14]
``` yaml
dependencies:
  browser: any
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  vector_math:
    git: https://github.com/johnmccutchan/vector_math.git
  stats:
    git: https://github.com/Dartist/stats.dart.git
```

Pub just hangs. Is this a Github config issue?
